In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.__version__

'2.2.1+cu121'

In [7]:
TENSOR = torch.tensor([[[[[1,2,3,4], [5,6,7,8]]]]])

In [8]:
TENSOR.ndim

5

In [9]:
TENSOR.shape

torch.Size([1, 1, 1, 2, 4])

Linear Regression Model

In [18]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1, requires_grad=True, dtype = torch.float))
        
        self.bias = nn.Parameter(torch.randn(1, requires_grad=True, dtype = torch.float))
        
    def forward(self, x:torch.Tensor)-> torch.Tensor:
        return self.weights * x + self.bias
    
        


In [19]:
torch.manual_seed(42)

In [20]:
model = LinearRegressionModel()

In [23]:
list(model.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [24]:
model.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [25]:
loss_fn = nn.L1Loss()

In [27]:
optimizer = torch.optim.SGD(params=model.parameters(), lr=0.01)

In [ ]:
#Training loop

epochs = 10

for epoch in epochs:
    
    model.train()
    
    y_pred_train = model(X_train)
    
    train_loss = loss_fn(y_pred_train, X_train)    
    optimizer.zero_grad()
    train_loss.backward()
    optimizer.step()
    
    #Testing loop

    model.eval()
    with torch.inference_mode():
        y_preds = model(X_test)
        test_loss = loss_fn(y_pred_test, X_test)
    y_preds

In [ ]:
#Saving a model
from pathlib import Path
MODEL_PATH = Path('models')
MODEL_PATH.mkdir(parents=True, exist_ok=True)

MODEL_NAME = 'model_name.pth'
MODEL_SAVE_PATH = MODEL_PATH  / MODEL_NAME

torch.save(obj=model.state_dict(), f=MODEL_SAVE_PATH)

In [ ]:
#Loading a model (CPU)

loaded_model = LinearRegressionModel()

loaded_model.load_state_dict(torch.load(f=MODEL_SAVE_PATH))

In [29]:
#Setting up device Agnostic Code

In [30]:
device = "cuda" if torch.cuda.is_available() == True else "cpu"

In [31]:
device

'cpu'

In [35]:
#LinearRegressionModelV2
class LinearRegressionModelV2(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_layer = nn.Linear(in_features=1, out_features=1)
        
        
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)

In [37]:
model_1 = LinearRegressionModelV2()
model_1.state_dict()

OrderedDict([('linear_layer.weight', tensor([[-0.4869]])),
             ('linear_layer.bias', tensor([0.5873]))])

In [41]:
model_1.to(device)
next(model_1.parameters()).device

device(type='cpu')

In [ ]:
#Put data to gpu too
X_train = X_train.to(device)
and so on

In [42]:
#Classification

In [43]:
import sklearn
from sklearn.datasets import make_circles

X, y = make_circles(1000, noise=0.03, random_state=42)

In [44]:
X, y

(array([[ 0.75424625,  0.23148074],
        [-0.75615888,  0.15325888],
        [-0.81539193,  0.17328203],
        ...,
        [-0.13690036, -0.81001183],
        [ 0.67036156, -0.76750154],
        [ 0.28105665,  0.96382443]]),
 array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
        0, 1, 1, 0, 1, 0, 1, 

In [46]:
X

array([[ 0.75424625,  0.23148074],
       [-0.75615888,  0.15325888],
       [-0.81539193,  0.17328203],
       ...,
       [-0.13690036, -0.81001183],
       [ 0.67036156, -0.76750154],
       [ 0.28105665,  0.96382443]])

In [48]:
import pandas as pd
df = pd.DataFrame({"X1":X[:, 0], "X2":X[:, 1], "label":y})

In [49]:
df

X1        X2  label
0    0.754246  0.231481      1
1   -0.756159  0.153259      1
2   -0.815392  0.173282      1
3   -0.393731  0.692883      1
4    0.442208 -0.896723      0
..        ...       ...    ...
995  0.244054  0.944125      0
996 -0.978655 -0.272373      0
997 -0.136900 -0.810012      1
998  0.670362 -0.767502      0
999  0.281057  0.963824      0

[1000 rows x 3 columns]

In [50]:
X = torch.from_numpy(X).type(torch.float) 
y = torch.from_numpy(y).type(torch.float) 

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [59]:
class BinaryClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(in_features=2, out_features=5)
        self.layer2 = nn.Linear(in_features=5, out_features=1)
        
    def forward(self, x):
        return self.layer2(self.layer1(x))

In [60]:
binary_model = BinaryClassifierModel().to(device)
binary_model

BinaryClassifierModel(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=1, bias=True)
)

In [84]:
#Using Sequential

binary_model_2 = nn.Sequential(
    nn.Linear(in_features=2, out_features=100),
    nn.ReLU(),
    nn.Linear(in_features=100, out_features=1),
    
).to(device)

In [85]:
binary_model_2.state_dict()

OrderedDict([('0.weight',
              tensor([[-2.6694e-01,  5.8414e-01],
                      [ 7.2337e-02, -5.2884e-01],
                      [ 4.4278e-03, -5.4919e-01],
                      [-1.5493e-01, -1.9444e-01],
                      [ 6.1212e-01,  2.1902e-01],
                      [-1.2330e-01,  1.1945e-01],
                      [-2.0412e-01,  2.7782e-01],
                      [ 2.7971e-01,  1.8989e-01],
                      [-2.7561e-01,  6.0327e-01],
                      [-1.0208e-01, -2.7529e-01],
                      [ 4.4287e-01,  5.7633e-01],
                      [ 7.0368e-01,  2.0949e-01],
                      [-2.4105e-01,  3.5913e-01],
                      [ 6.0667e-01, -6.9355e-01],
                      [-8.7601e-02, -4.8222e-01],
                      [ 1.3178e-01,  2.9245e-01],
                      [-1.4608e-01, -5.9155e-02],
                      [ 3.1828e-01, -1.1884e-01],
                      [-5.9381e-01,  5.6578e-01],
                      [-

In [88]:
loss_fn = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(params=binary_model_2.parameters(), lr=0.1)

In [89]:
def accuracy(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item()
    acc = (correct/len(y_pred))
    
    return acc
    

In [90]:
epochs = 500

X_train, X_test = X_train.to(device), X_test.to(device)
y_train, y_test = y_train.to(device), y_test.to(device)

for epoch in range(epochs):
    
    model.train()
    
    y_logits = binary_model_2(X_train).squeeze()
    y_pred = torch.round(torch.sigmoid(y_logits))
    train_loss = loss_fn(y_logits, y_train)
    acc_train = accuracy(y_pred=y_pred, y_true=y_train)
    optimizer.zero_grad()
    train_loss.backward()
    optimizer.step()
    
    model.eval()
    with torch.inference_mode():
        test_logits = binary_model_2(X_test).squeeze()
        test_pred = torch.round(torch.sigmoid(test_logits))
        
        test_loss = loss_fn(y_test, test_pred)
        
        acc_test = accuracy(y_pred=test_pred, y_true=y_test)
        
        print("Test loss: ", test_loss, "Train Loss: ", train_loss, "Train Accuracy: ", acc_train, "Test Accuracy: ", acc_test)

Test loss:  tensor(0.9908) Train Loss:  tensor(0.6978, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.55 Test Accuracy:  0.52
Test loss:  tensor(0.9908) Train Loss:  tensor(1.3205, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.49142857142857144 Test Accuracy:  0.52
Test loss:  tensor(0.5108) Train Loss:  tensor(0.7463, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.49142857142857144 Test Accuracy:  0.48
Test loss:  tensor(0.5108) Train Loss:  tensor(0.7338, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.5085714285714286 Test Accuracy:  0.48
Test loss:  tensor(0.5108) Train Loss:  tensor(0.8362, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.5085714285714286 Test Accuracy:  0.48
Test loss:  tensor(0.5108) Train Loss:  tensor(0.8151, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.5085714285714286 Test Accuracy:  0.48
Test loss:  tensor(0.5275) Train Loss:  tensor

In [91]:
#Multi-class classification
from sklearn.datasets import make_blobs
X , y = make_blobs(n_samples=1000, n_features=2, centers=4, random_state=42)

In [92]:
X, y

(array([[-8.55503989,  7.06461794],
        [-6.13753182, -6.58081701],
        [-6.32130028, -6.8041042 ],
        ...,
        [ 3.69047995,  4.60555175],
        [-7.48913939, -7.0670809 ],
        [-9.40049578,  7.11430104]]),
 array([3, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 3, 0, 2, 2, 2, 0, 0, 0, 1, 1, 3,
        3, 3, 1, 1, 0, 0, 2, 1, 2, 2, 2, 0, 0, 3, 2, 1, 3, 3, 1, 2, 1, 3,
        1, 3, 0, 1, 3, 1, 2, 0, 1, 3, 0, 3, 0, 0, 0, 2, 2, 0, 2, 3, 1, 0,
        2, 2, 1, 0, 3, 0, 1, 2, 1, 3, 1, 0, 1, 0, 2, 0, 0, 0, 1, 3, 2, 2,
        0, 0, 0, 0, 1, 1, 3, 1, 3, 0, 1, 2, 1, 3, 3, 0, 3, 1, 1, 0, 2, 0,
        3, 2, 1, 1, 1, 1, 2, 3, 2, 1, 0, 2, 3, 1, 3, 2, 1, 3, 2, 1, 0, 2,
        1, 3, 1, 3, 0, 2, 1, 1, 0, 0, 3, 3, 3, 1, 1, 0, 0, 0, 0, 3, 2, 2,
        0, 1, 0, 1, 1, 3, 2, 0, 1, 2, 0, 0, 1, 2, 3, 2, 1, 0, 0, 1, 0, 3,
        2, 3, 2, 3, 1, 1, 0, 2, 0, 2, 1, 3, 0, 2, 1, 0, 1, 1, 0, 3, 2, 2,
        2, 3, 0, 2, 1, 0, 1, 1, 2, 0, 1, 2, 2, 3, 2, 2, 1, 0, 2, 0, 3, 1,
        3, 3, 2, 0, 3, 0, 1, 

In [93]:
X = torch.from_numpy(X).type(torch.float) 
y = torch.from_numpy(y).type(torch.float) 

In [94]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)