In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.__version__

'2.2.1+cu121'

In [7]:
TENSOR = torch.tensor([[[[[1,2,3,4], [5,6,7,8]]]]])

In [8]:
TENSOR.ndim

5

In [9]:
TENSOR.shape

torch.Size([1, 1, 1, 2, 4])

Linear Regression Model

In [18]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1, requires_grad=True, dtype = torch.float))
        
        self.bias = nn.Parameter(torch.randn(1, requires_grad=True, dtype = torch.float))
        
    def forward(self, x:torch.Tensor)-> torch.Tensor:
        return self.weights * x + self.bias
    
        


In [19]:
torch.manual_seed(42)

In [20]:
model = LinearRegressionModel()

In [23]:
list(model.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [24]:
model.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [25]:
loss_fn = nn.L1Loss()

In [27]:
optimizer = torch.optim.SGD(params=model.parameters(), lr=0.01)

In [ ]:
#Training loop

epochs = 10

for epoch in epochs:
    
    model.train()
    
    y_pred_train = model(X_train)
    
    train_loss = loss_fn(y_pred_train, X_train)    
    optimizer.zero_grad()
    train_loss.backward()
    optimizer.step()
    
    #Testing loop

    model.eval()
    with torch.inference_mode():
        y_preds = model(X_test)
        test_loss = loss_fn(y_pred_test, X_test)
    y_preds

In [3]:
#Saving a model
from pathlib import Path
MODEL_PATH = Path('models')
MODEL_PATH.mkdir(parents=True, exist_ok=True)

MODEL_NAME = 'model_name.pth'
MODEL_SAVE_PATH = MODEL_PATH  / MODEL_NAME

torch.save(obj=model.state_dict(), f=MODEL_SAVE_PATH)

NameError: name 'model' is not defined

In [ ]:
#Loading a model (CPU)

loaded_model = LinearRegressionModel()

loaded_model.load_state_dict(torch.load(f=MODEL_SAVE_PATH))

In [29]:
#Setting up device Agnostic Code

In [4]:
device = "cuda" if torch.cuda.is_available() == True else "cpu"

In [31]:
device

'cpu'

In [35]:
#LinearRegressionModelV2
class LinearRegressionModelV2(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_layer = nn.Linear(in_features=1, out_features=1)
        
        
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)

In [37]:
model_1 = LinearRegressionModelV2()
model_1.state_dict()

OrderedDict([('linear_layer.weight', tensor([[-0.4869]])),
             ('linear_layer.bias', tensor([0.5873]))])

In [41]:
model_1.to(device)
next(model_1.parameters()).device

device(type='cpu')

In [ ]:
#Put data to gpu too
X_train = X_train.to(device)
and so on

In [42]:
#Classification

In [5]:
import sklearn
from sklearn.datasets import make_circles

X, y = make_circles(1000, noise=0.03, random_state=42)

In [44]:
X, y

(array([[ 0.75424625,  0.23148074],
        [-0.75615888,  0.15325888],
        [-0.81539193,  0.17328203],
        ...,
        [-0.13690036, -0.81001183],
        [ 0.67036156, -0.76750154],
        [ 0.28105665,  0.96382443]]),
 array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
        0, 1, 1, 0, 1, 0, 1, 

In [46]:
X

array([[ 0.75424625,  0.23148074],
       [-0.75615888,  0.15325888],
       [-0.81539193,  0.17328203],
       ...,
       [-0.13690036, -0.81001183],
       [ 0.67036156, -0.76750154],
       [ 0.28105665,  0.96382443]])

In [6]:
import pandas as pd
df = pd.DataFrame({"X1":X[:, 0], "X2":X[:, 1], "label":y})

In [49]:
df

X1        X2  label
0    0.754246  0.231481      1
1   -0.756159  0.153259      1
2   -0.815392  0.173282      1
3   -0.393731  0.692883      1
4    0.442208 -0.896723      0
..        ...       ...    ...
995  0.244054  0.944125      0
996 -0.978655 -0.272373      0
997 -0.136900 -0.810012      1
998  0.670362 -0.767502      0
999  0.281057  0.963824      0

[1000 rows x 3 columns]

In [50]:
X = torch.from_numpy(X).type(torch.float) 
y = torch.from_numpy(y).type(torch.float) 

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [59]:
class BinaryClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(in_features=2, out_features=5)
        self.layer2 = nn.Linear(in_features=5, out_features=1)
        
    def forward(self, x):
        return self.layer2(self.layer1(x))

In [60]:
binary_model = BinaryClassifierModel().to(device)
binary_model

BinaryClassifierModel(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=1, bias=True)
)

In [84]:
#Using Sequential

binary_model_2 = nn.Sequential(
    nn.Linear(in_features=2, out_features=100),
    nn.ReLU(),
    nn.Linear(in_features=100, out_features=1),
    
).to(device)

In [85]:
binary_model_2.state_dict()

OrderedDict([('0.weight',
              tensor([[-2.6694e-01,  5.8414e-01],
                      [ 7.2337e-02, -5.2884e-01],
                      [ 4.4278e-03, -5.4919e-01],
                      [-1.5493e-01, -1.9444e-01],
                      [ 6.1212e-01,  2.1902e-01],
                      [-1.2330e-01,  1.1945e-01],
                      [-2.0412e-01,  2.7782e-01],
                      [ 2.7971e-01,  1.8989e-01],
                      [-2.7561e-01,  6.0327e-01],
                      [-1.0208e-01, -2.7529e-01],
                      [ 4.4287e-01,  5.7633e-01],
                      [ 7.0368e-01,  2.0949e-01],
                      [-2.4105e-01,  3.5913e-01],
                      [ 6.0667e-01, -6.9355e-01],
                      [-8.7601e-02, -4.8222e-01],
                      [ 1.3178e-01,  2.9245e-01],
                      [-1.4608e-01, -5.9155e-02],
                      [ 3.1828e-01, -1.1884e-01],
                      [-5.9381e-01,  5.6578e-01],
                      [-

In [88]:
loss_fn = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(params=binary_model_2.parameters(), lr=0.1)

In [89]:
def accuracy(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item()
    acc = (correct/len(y_pred))
    
    return acc
    

In [90]:
epochs = 500

X_train, X_test = X_train.to(device), X_test.to(device)
y_train, y_test = y_train.to(device), y_test.to(device)

for epoch in range(epochs):
    
    model.train()
    
    y_logits = binary_model_2(X_train).squeeze()
    y_pred = torch.round(torch.sigmoid(y_logits))
    train_loss = loss_fn(y_logits, y_train)
    acc_train = accuracy(y_pred=y_pred, y_true=y_train)
    optimizer.zero_grad()
    train_loss.backward()
    optimizer.step()
    
    model.eval()
    with torch.inference_mode():
        test_logits = binary_model_2(X_test).squeeze()
        test_pred = torch.round(torch.sigmoid(test_logits))
        
        test_loss = loss_fn(y_test, test_pred)
        
        acc_test = accuracy(y_pred=test_pred, y_true=y_test)
        
        print("Test loss: ", test_loss, "Train Loss: ", train_loss, "Train Accuracy: ", acc_train, "Test Accuracy: ", acc_test)

Test loss:  tensor(0.9908) Train Loss:  tensor(0.6978, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.55 Test Accuracy:  0.52
Test loss:  tensor(0.9908) Train Loss:  tensor(1.3205, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.49142857142857144 Test Accuracy:  0.52
Test loss:  tensor(0.5108) Train Loss:  tensor(0.7463, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.49142857142857144 Test Accuracy:  0.48
Test loss:  tensor(0.5108) Train Loss:  tensor(0.7338, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.5085714285714286 Test Accuracy:  0.48
Test loss:  tensor(0.5108) Train Loss:  tensor(0.8362, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.5085714285714286 Test Accuracy:  0.48
Test loss:  tensor(0.5108) Train Loss:  tensor(0.8151, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>) Train Accuracy:  0.5085714285714286 Test Accuracy:  0.48
Test loss:  tensor(0.5275) Train Loss:  tensor

In [91]:
#Multi-class classification
from sklearn.datasets import make_blobs
X , y = make_blobs(n_samples=1000, n_features=2, centers=4, random_state=42)

In [92]:
X, y

(array([[-8.55503989,  7.06461794],
        [-6.13753182, -6.58081701],
        [-6.32130028, -6.8041042 ],
        ...,
        [ 3.69047995,  4.60555175],
        [-7.48913939, -7.0670809 ],
        [-9.40049578,  7.11430104]]),
 array([3, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 3, 0, 2, 2, 2, 0, 0, 0, 1, 1, 3,
        3, 3, 1, 1, 0, 0, 2, 1, 2, 2, 2, 0, 0, 3, 2, 1, 3, 3, 1, 2, 1, 3,
        1, 3, 0, 1, 3, 1, 2, 0, 1, 3, 0, 3, 0, 0, 0, 2, 2, 0, 2, 3, 1, 0,
        2, 2, 1, 0, 3, 0, 1, 2, 1, 3, 1, 0, 1, 0, 2, 0, 0, 0, 1, 3, 2, 2,
        0, 0, 0, 0, 1, 1, 3, 1, 3, 0, 1, 2, 1, 3, 3, 0, 3, 1, 1, 0, 2, 0,
        3, 2, 1, 1, 1, 1, 2, 3, 2, 1, 0, 2, 3, 1, 3, 2, 1, 3, 2, 1, 0, 2,
        1, 3, 1, 3, 0, 2, 1, 1, 0, 0, 3, 3, 3, 1, 1, 0, 0, 0, 0, 3, 2, 2,
        0, 1, 0, 1, 1, 3, 2, 0, 1, 2, 0, 0, 1, 2, 3, 2, 1, 0, 0, 1, 0, 3,
        2, 3, 2, 3, 1, 1, 0, 2, 0, 2, 1, 3, 0, 2, 1, 0, 1, 1, 0, 3, 2, 2,
        2, 3, 0, 2, 1, 0, 1, 1, 2, 0, 1, 2, 2, 3, 2, 2, 1, 0, 2, 0, 3, 1,
        3, 3, 2, 0, 3, 0, 1, 

In [93]:
X = torch.from_numpy(X).type(torch.float) 
y = torch.from_numpy(y).type(torch.LongTensor) # It needs the class indices to be integers

In [94]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [95]:
#Same model arhcitecture

In [96]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(params=binary_model.parameters(), lr=0.01)

In [ ]:
#get logits
y_preds_blobs = torch.softmax(y_logits, dim=1)
y_pred = torch.argmax(y_preds_blobs, dim=1)

In [97]:
##CV


In [8]:
import torchvision 
from torchvision import datasets
from torchvision import transforms
from torchvision.transforms import ToTensor

/home/yuvrajsingh/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [175]:
train_data = datasets.FashionMNIST(
    root='data',
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=None
)

In [176]:
test_data = datasets.FashionMNIST(
    root='data',
    train=False,
    download=True,
    transform=ToTensor(),
    target_transform=None
)

In [177]:
len(train_data), len(test_data)

(60000, 10000)

In [178]:

class_names = train_data.classes
class_names

['T-shirt/top',
 'Trouser',
 'Pullover',
 'Dress',
 'Coat',
 'Sandal',
 'Shirt',
 'Sneaker',
 'Bag',
 'Ankle boot']

In [179]:
class_names_to_id = train_data.class_to_idx

In [180]:
from torch.utils.data import DataLoader

In [181]:
train_dataloader = DataLoader(
    dataset=train_data,
    batch_size=32,
    shuffle=True    
)

In [182]:
test_dataloader = DataLoader(
    dataset=test_data,
    batch_size=32,
    shuffle=False
)

In [9]:
class FashionMNISTModelV2(nn.Module):
  def __init__(self, input_shape: int, hidden_units: int, output_shape: int):
    super().__init__()
    self.conv_block_1 = nn.Sequential(
       
        nn.Conv2d(in_channels=input_shape, 
                  out_channels=hidden_units,
                  kernel_size=3,
                  stride=1,
                  padding=1), 
        nn.ReLU(),
        nn.Conv2d(in_channels=hidden_units,
                  out_channels=hidden_units,
                  kernel_size=3,
                  stride=1,
                  padding=1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2)
    )
    self.conv_block_2 = nn.Sequential(
        nn.Conv2d(in_channels=hidden_units,
                  out_channels=hidden_units,
                  kernel_size=3,
                  stride=1,
                  padding=1),
        nn.ReLU(),
        nn.Conv2d(in_channels=hidden_units,
                  out_channels=hidden_units,
                  kernel_size=3,
                  stride=1,
                  padding=1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2)
    )
    self.classifier = nn.Sequential(
        nn.Flatten(),
        nn.Linear(in_features=hidden_units*256, # there's a trick to calculating this...
                  out_features=output_shape)
    )
#the trick
# img_batch, img_label = next(iter(train_dataloader))
# model_cnn(img_batch)

  def forward(self, x):
    x = self.conv_block_1(x)
    # print(f"Output shape of conv_block_1: {x.shape}")
    x = self.conv_block_2(x) 
    # print(f"Output shape of conv_block_2: {x.shape}")
    x = self.classifier(x)
    # print(f"Output shape of classifier: {x.shape}")
    return x

tensor([[0.1185, 0.0484, 0.1040],
        [0.1317, 0.0532, 0.1127],
        [0.1262, 0.0549, 0.1190],
        [0.1190, 0.0458, 0.1125],
        [0.1246, 0.0464, 0.1048],
        [0.0968, 0.0576, 0.1049],
        [0.1244, 0.0483, 0.1133],
        [0.1143, 0.0298, 0.1039],
        [0.1374, 0.0598, 0.1148],
        [0.1304, 0.0462, 0.1198],
        [0.1240, 0.0435, 0.1277],
        [0.1348, 0.0443, 0.1082],
        [0.1281, 0.0490, 0.1145],
        [0.1116, 0.0493, 0.1000],
        [0.1308, 0.0484, 0.1193],
        [0.1340, 0.0492, 0.1110],
        [0.1207, 0.0448, 0.1105],
        [0.0963, 0.0233, 0.0996],
        [0.1189, 0.0524, 0.1086],
        [0.1103, 0.0422, 0.1073],
        [0.1144, 0.0562, 0.1111],
        [0.1298, 0.0567, 0.1137],
        [0.1296, 0.0677, 0.1194],
        [0.1304, 0.0468, 0.1030],
        [0.1057, 0.0404, 0.0991],
        [0.1023, 0.0374, 0.0986],
        [0.1062, 0.0411, 0.1037],
        [0.1377, 0.0538, 0.1253],
        [0.1348, 0.0575, 0.1147],
        [0.127

In [10]:
model_cnn = FashionMNISTModelV2(input_shape=3, output_shape=len(class_names), hidden_units=100)
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_cnn.parameters(), lr=0.1)

NameError: name 'class_names' is not defined

In [11]:
data_iter = iter(train_dataloader)
images, labels = next(data_iter)
images, labels

NameError: name 'train_dataloader' is not defined

In [252]:
epochs = 50
for epoch in range(epochs):
    train_loss = 0
    
    for batch, (X, y) in enumerate(train_dataloader_augmented):
        model_cnn.train()
        
        y_pred = model_cnn(X)
        loss = loss_fn(y_pred, y)
        train_loss += loss
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    train_loss /= len(train_dataloader)
    test_loss = 0
    test_acc = 0
    model_cnn.eval()
    with torch.inference_mode():
        for X_test, y_test in test_dataloader_augmented:
            test_pred = model_cnn(X_test)
            test_loss += loss_fn(test_pred, y_test)
            probs = torch.softmax(test_pred, dim=1)
            test_acc += accuracy(y_pred=torch.argmax(probs, dim=1), y_true=y_test)
        test_loss /= len(test_dataloader)
        test_acc /= len(train_dataloader)
        
    print("Test accuracy: ", test_acc, "Test loss: ", test_loss)

Test accuracy:  0.07421875 Test loss:  tensor(548671.6875)
Test accuracy:  0.09765625 Test loss:  tensor(173.7873)
Test accuracy:  0.09765625 Test loss:  tensor(70.1312)
Test accuracy:  0.203125 Test loss:  tensor(7.9468)
Test accuracy:  0.203125 Test loss:  tensor(1.1196)


In [12]:
#Custom Datasets

import requests
import zipfile
from pathlib import Path

# Setup path to a data folder
data_path = Path("data2/")
image_path = data_path / "pizza_steak_sushi"

# If the image folder doesn't exist, download it and prepare it...
if image_path.is_dir():
  print(f"{image_path} directory already exists... skipping download")
else: 
  print(f"{image_path} does not exist, creating one...")
  image_path.mkdir(parents=True, exist_ok=True)

# Download pizza, steak and suhsi data
with open(data_path / "pizza_steak_sushi.zip", "wb") as f:
  request = requests.get("https://github.com/mrdbourke/pytorch-deep-learning/raw/main/data/pizza_steak_sushi.zip")
  print("Downloading pizza, steak, suhsi data...")
  f.write(request.content)

# Unzip pizza, steak, sushi data
with zipfile.ZipFile(data_path / "pizza_steak_sushi.zip", "r") as zip_ref:
  print("Unzipping pizza, steak and sushi data...")
  zip_ref.extractall(image_path)

data2/pizza_steak_sushi directory already exists... skipping download
Unzipping pizza, steak and sushi data...


In [13]:
#Transforms
data_transform = transforms.Compose([
    transforms.Resize(size=(64,64)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor()
])

In [14]:

# Setup train and testing paths
train_dir = image_path / "train"
test_dir = image_path / "test"

train_dir, test_dir

(PosixPath('data2/pizza_steak_sushi/train'),
 PosixPath('data2/pizza_steak_sushi/test'))

In [15]:
from torchvision import datasets

In [16]:
train_data = datasets.ImageFolder(train_dir, transform=data_transform, target_transform=None)
test_data = datasets.ImageFolder(test_dir, transform=data_transform, target_transform=None)


In [17]:
class_names = train_data.classes

In [18]:
class_dict = train_data.class_to_idx

In [19]:
import os

In [20]:
train_dataloader = DataLoader(dataset=train_data, num_workers=os.cpu_count(), batch_size=32, shuffle=True)

NameError: name 'DataLoader' is not defined

In [ ]:
test_dataloader = DataLoader(dataset=test_data, num_workers=os.cpu_count(), batch_size=32, shuffle=False)

In [ ]:
#Getting summary
from torchinfo import summary

In [ ]:
summary(model_cnn, input_size=[1, 3, 64, 64])

Layer (type:depth-idx)                   Output Shape              Param #
FashionMNISTModelV2                      [1, 3]                    --
├─Sequential: 1-1                        [1, 10, 32, 32]           --
│    └─Conv2d: 2-1                       [1, 10, 64, 64]           280
│    └─ReLU: 2-2                         [1, 10, 64, 64]           --
│    └─Conv2d: 2-3                       [1, 10, 64, 64]           910
│    └─ReLU: 2-4                         [1, 10, 64, 64]           --
│    └─MaxPool2d: 2-5                    [1, 10, 32, 32]           --
├─Sequential: 1-2                        [1, 10, 16, 16]           --
│    └─Conv2d: 2-6                       [1, 10, 32, 32]           910
│    └─ReLU: 2-7                         [1, 10, 32, 32]           --
│    └─Conv2d: 2-8                       [1, 10, 32, 32]           910
│    └─ReLU: 2-9                         [1, 10, 32, 32]           --
│    └─MaxPool2d: 2-10                   [1, 10, 16, 16]           --
├─Sequentia

In [21]:
#Data Augmentation

In [22]:
train_transform_trivial = transforms.Compose([
    transforms.Resize(size=(64,64)),
    transforms.TrivialAugmentWide(num_magnitude_bins=31),
    transforms.ToTensor()
])

In [23]:
test_transform_trivial = transforms.Compose([
    transforms.Resize(size=(64,64)),
    # transforms.TrivialAugmentWide(num_magnitude_bins=31),
    transforms.ToTensor()
])

In [24]:
train_data_augmented = datasets.ImageFolder(root=train_dir, transform=train_transform_trivial)

In [25]:
test_data_augmented = datasets.ImageFolder(root=test_dir, transform=test_transform_trivial)

In [26]:
train_dataloader_augmented = DataLoader(dataset=train_data_augmented, num_workers=os.cpu_count(), batch_size=32, shuffle=True)

NameError: name 'DataLoader' is not defined

In [27]:
test_dataloader_augmented = DataLoader(dataset=test_data_augmented, num_workers=os.cpu_count(), batch_size=32, shuffle=False)

NameError: name 'DataLoader' is not defined

In [28]:
#Predictions with custom image

# Download custom image
import requests

# Setup custom image path
custom_image_path = data_path / "04-pizza-dad.jpeg"

# Download the image if it doesn't already exist
if not custom_image_path.is_file():
  with open(custom_image_path, "wb") as f:
    # When downloading from GitHub, need to use the "raw" file link
    request = requests.get("https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/04-pizza-dad.jpeg")
    print(f"Downloading {custom_image_path}...")
    f.write(request.content)
else:
  print(f"{custom_image_path} already exists, skipping download...")

data2/04-pizza-dad.jpeg already exists, skipping download...


In [31]:
custom_image_path_uint8 = torchvision.io.read_image(str(custom_image_path)).type(torch.float32) / 255.